# docker-compose.yml
# version: '3.8'

services:
  symfony_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_test
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - ./www_app:/var/www
#    command: >
#      sh -c "symfony server:start --no-tls --listen-ip=0.0.0.0 --daemon"
    tty: true